import type {
  MemberDirectoryEntry,
  ProgramMessage,
  ProgramSnapshot,
} from "@/types";
import type {
  MessageReactionSnapshot,
  MessageReactionUser,
} from "@/features/conversation/reactions";

const createdAt = "2026-08-01T09:00:00.000Z";
const updatedAt = "2026-08-07T09:00:00.000Z";

const host: MemberDirectoryEntry = {
  id: "design-lab-host",
  name: "김유진",
  imageUrl: null,
  occupation: "Architect",
  bio: null,
  interests: ["전시", "재료"],
};

export const designLabProgramSnapshots: ProgramSnapshot[] = [
  {
    program: {
      id: "program-gathering-028",
      code: "OA / G028",
      type: "GATHERING",
      title: "리움 전시 같이 보기",
      description: "작품을 함께 보고 각자의 관찰을 짧게 나눕니다.",
      hostId: host.id,
      startAt: "2026-08-22T05:00:00.000Z",
      endAt: "2026-08-22T08:00:00.000Z",
      location: "리움미술관",
      mapUrl: null,
      capacity: 8,
      status: "OPEN",
      coverImageId: null,
      createdAt,
      updatedAt,
      detail: {
        programId: "program-gathering-028",
        category: "EXHIBITION",
        meetingPoint: "1층 로비",
        recruitmentDeadline: "2026-08-20T14:59:00.000Z",
        waitlistEnabled: true,
        cost: {
          type: "INDIVIDUAL_PURCHASE",
          estimatedPrice: 18_000,
          purchaseUrl: null,
          purchaseNote: "14시 회차를 각자 구매해 주세요.",
        },
        bringItems: null,
        notice: null,
      },
    },
    host,
    participantCounts: { confirmed: 6, waitlist: 2, applied: 0, cancelled: 1 },
    record: null,
    displayStatus: "OPEN",
  },
  {
    program: {
      id: "program-gathering-029",
      code: "OA / G029",
      type: "GATHERING",
      title: "작은 목재 오브젝트 만들기",
      description: "손에 잡히는 작은 목재 오브젝트를 함께 만듭니다.",
      hostId: host.id,
      startAt: "2026-08-29T05:00:00.000Z",
      endAt: "2026-08-29T08:00:00.000Z",
      location: "성수동 재료실",
      mapUrl: null,
      capacity: 6,
      status: "OPEN",
      coverImageId: null,
      createdAt,
      updatedAt,
      detail: {
        programId: "program-gathering-029",
        category: "WORKSHOP",
        meetingPoint: "건물 1층 출입구",
        recruitmentDeadline: null,
        waitlistEnabled: false,
        cost: {
          type: "HOST_COLLECT",
          participationFee: 25_000,
          feeIncludes: "재료와 공구",
          paymentInfo: null,
          paymentDeadline: null,
          cancellationPolicy: null,
        },
        bringItems: "작업복",
        notice: null,
      },
    },
    host,
    participantCounts: { confirmed: 4, waitlist: 0, applied: 0, cancelled: 0 },
    record: null,
    displayStatus: "OPEN",
  },
  {
    program: {
      id: "program-reading-030",
      code: "OA / R014",
      type: "READING",
      title: "건축 없는 건축: 장소와 관계를 다시 읽는 긴 제목의 테스트",
      description: "텍스트를 읽고 질문을 나눕니다.",
      hostId: host.id,
      startAt: "2026-08-19T10:30:00.000Z",
      endAt: "2026-08-19T12:00:00.000Z",
      location: "서울특별시 종로구의 아주 긴 장소 이름을 가진 작은 서점",
      mapUrl: null,
      capacity: 12,
      status: "OPEN",
      coverImageId: null,
      createdAt,
      updatedAt,
      detail: {
        programId: "program-reading-030",
        resourceTitle: "건축 없는 건축",
      },
    },
    host,
    participantCounts: { confirmed: 10, waitlist: 1, applied: 0, cancelled: 2 },
    record: null,
    displayStatus: "HAPPENING",
  },
];

export const designLabCurrentUser: MessageReactionUser = {
  id: "design-lab-current-user",
  name: "최유진",
  imageUrl: null,
  seasons: ["3기"],
};

const reactionUsers: MessageReactionUser[] = [
  designLabCurrentUser,
  { id: "design-lab-user-2", name: "김민지", imageUrl: null, seasons: ["2기"] },
  { id: "design-lab-user-3", name: "이현우", imageUrl: null, seasons: ["1기", "3기"] },
];

export const designLabMessages: ProgramMessage[] = [
  {
    id: "design-lab-notice",
    programId: "design-lab-gathering-exhibition",
    authorId: host.id,
    type: "NOTICE",
    content: "집결 장소가 1층 로비에서 매표소 앞으로 변경되었습니다.",
    parentId: null,
    isPinned: true,
    isHidden: false,
    createdAt: "2026-08-22T03:10:00.000Z",
    editedAt: null,
  },
  {
    id: "design-lab-question",
    programId: "design-lab-gathering-exhibition",
    authorId: reactionUsers[1].id,
    type: "QUESTION",
    content: "티켓은 각자 구매하면 되나요? 긴 질문에서도 작성자와 시간이 본문보다 앞서 보이지 않는지 확인합니다.",
    parentId: null,
    isPinned: false,
    isHidden: false,
    createdAt: "2026-08-22T03:18:00.000Z",
    editedAt: null,
  },
  {
    id: "design-lab-reply",
    programId: "design-lab-gathering-exhibition",
    authorId: host.id,
    type: "CHAT",
    content: "네. 14시 회차로 각자 구매해 주세요.",
    parentId: "design-lab-question",
    isPinned: false,
    isHidden: false,
    createdAt: "2026-08-22T03:21:00.000Z",
    editedAt: null,
  },
  {
    id: "design-lab-chat",
    programId: "design-lab-gathering-exhibition",
    authorId: designLabCurrentUser.id,
    type: "CHAT",
    content: "저는 10분 정도 일찍 도착할게요.",
    parentId: null,
    isPinned: false,
    isHidden: false,
    createdAt: "2026-08-22T04:01:00.000Z",
    editedAt: null,
  },
];

export const designLabInitialReactions: MessageReactionSnapshot[] = [
  {
    id: "design-lab-reaction-1",
    programId: "design-lab-gathering-exhibition",
    messageId: "design-lab-notice",
    userId: reactionUsers[1].id,
    emoji: "✅",
    createdAt,
    updatedAt,
    user: reactionUsers[1],
  },
  {
    id: "design-lab-reaction-2",
    programId: "design-lab-gathering-exhibition",
    messageId: "design-lab-notice",
    userId: reactionUsers[2].id,
    emoji: "✅",
    createdAt,
    updatedAt,
    user: reactionUsers[2],
  },
  {
    id: "design-lab-reaction-3",
    programId: "design-lab-gathering-exhibition",
    messageId: "design-lab-question",
    userId: designLabCurrentUser.id,
    emoji: "👍",
    createdAt,
    updatedAt,
    user: designLabCurrentUser,
  },
  {
    id: "design-lab-reaction-4",
    programId: "design-lab-gathering-exhibition",
    messageId: "design-lab-question",
    userId: reactionUsers[2].id,
    emoji: "👍",
    createdAt,
    updatedAt,
    user: reactionUsers[2],
  },
];
