import { MOCK_CURRENT_USER_ID, MOCK_SCHEMA_VERSION } from "../../constants";
import type { MessageReaction } from "../../features/conversation/reactions";
import type {
  PageContent,
  Participation,
  PaymentStatus,
  Program,
  ProgramApproval,
  ProgramMessage,
  ProgramRecord,
  User,
} from "../../types";
import type { MockRepositoryState } from "./contracts";

export const MOCK_PROGRAM_IDS = {
  talk: "program-talk-027",
  exhibition: "program-gathering-028",
  workshop: "program-gathering-029",
  reading: "program-reading-030",
} as const;

export const MOCK_PENDING_USER_ID = "user-pending";

const MEMBER_IDS = [
  "user-member-1",
  "user-member-2",
  "user-member-3",
  "user-member-4",
  "user-member-5",
  "user-member-6",
] as const;

function user(
  id: string,
  name: string,
  status: User["status"] = "MEMBER",
  occupation: string | null = null,
): User {
  return {
    id,
    name,
    email: `${id}@example.com`,
    imageUrl: null,
    occupation,
    bio: null,
    interests: [],
    status,
    createdAt: "2026-01-10T00:00:00.000Z",
  };
}

function participation(
  id: string,
  programId: string,
  userId: string,
  joinedAt: string,
  paymentStatus: PaymentStatus = "NOT_REQUIRED",
): Participation {
  return {
    id,
    programId,
    userId,
    status: "CONFIRMED",
    paymentStatus,
    joinedAt,
  };
}

export function createMockRepositoryState(): MockRepositoryState {
  const users: User[] = [
    user(MOCK_CURRENT_USER_ID, "오민서", "MEMBER", "건축 디자이너"),
    user("user-admin", "김도윤", "ADMIN", "OMNIVORE 운영"),
    user("user-host-exhibition", "김서연", "MEMBER", "큐레이터"),
    user("user-host-workshop", "박지호", "MEMBER", "목공 디자이너"),
    user("user-host-reading", "이하은", "MEMBER", "에디터"),
    user(MEMBER_IDS[0], "정우진", "MEMBER", "건축가"),
    user(MEMBER_IDS[1], "한유나", "MEMBER", "공간 디자이너"),
    user(MEMBER_IDS[2], "조현우", "MEMBER", "학생"),
    user(MEMBER_IDS[3], "임수아", "MEMBER", "브랜드 디자이너"),
    user(MEMBER_IDS[4], "윤태경", "MEMBER", "연구자"),
    user(MEMBER_IDS[5], "최가은", "MEMBER", "에디터"),
    user(MOCK_PENDING_USER_ID, "서지안", "PENDING", "건축학도"),
  ];

  const participatingSeasonsByUserId: Record<string, string[]> = {
    [MOCK_CURRENT_USER_ID]: ["3기"],
    "user-admin": ["1기", "2기", "3기"],
    "user-host-exhibition": ["2기", "3기"],
    "user-host-workshop": ["3기"],
    "user-host-reading": ["2기", "3기"],
    [MEMBER_IDS[0]]: ["3기"],
    [MEMBER_IDS[1]]: ["3기"],
    [MEMBER_IDS[2]]: ["2기", "3기"],
    [MEMBER_IDS[3]]: ["3기"],
    [MEMBER_IDS[4]]: ["1기", "2기", "3기"],
    [MEMBER_IDS[5]]: ["2기"],
    [MOCK_PENDING_USER_ID]: ["3기"],
  };

  const programs: Program[] = [
    {
      id: MOCK_PROGRAM_IDS.talk,
      code: "OA / T027",
      type: "TALK",
      title: "AI 시대의 인간 가치 창출과 데이터 기반 브랜드 전략",
      description: "AI 시대에 인간의 역할과 브랜드가 만드는 고유한 가치를 살펴봅니다.",
      hostId: "user-admin",
      startAt: "2026-08-07T10:30:00.000Z",
      endAt: "2026-08-07T12:00:00.000Z",
      location: "성수 OA SPACE",
      mapUrl: null,
      capacity: null,
      status: "COMPLETED",
      coverImageId: null,
      createdAt: "2026-07-15T03:00:00.000Z",
      updatedAt: "2026-08-07T13:00:00.000Z",
      detail: {
        programId: MOCK_PROGRAM_IDS.talk,
        origin: "OMNIVORE",
        subtitle: null,
        speakerName: "최장수",
        speakerAffiliation: "릴레멘트 컴퍼니",
        speakerBio: null,
        organizer: "OMNIVORE ARCHITECT",
        address: null,
        sourceUrl: null,
        registrationType: "OMNIVORE",
        registrationUrl: null,
      },
    },
    {
      id: MOCK_PROGRAM_IDS.exhibition,
      code: "OA / G028",
      type: "GATHERING",
      title: "리움 전시 같이 보기",
      description: "리움미술관의 전시를 함께 보고 각자의 시선으로 짧게 이야기합니다.",
      hostId: "user-host-exhibition",
      startAt: "2026-08-22T05:00:00.000Z",
      endAt: "2026-08-22T08:00:00.000Z",
      location: "리움미술관",
      mapUrl: "https://maps.google.com/?q=Leeum+Museum",
      capacity: 8,
      status: "OPEN",
      coverImageId: null,
      createdAt: "2026-08-01T01:00:00.000Z",
      updatedAt: "2026-08-01T01:00:00.000Z",
      detail: {
        programId: MOCK_PROGRAM_IDS.exhibition,
        category: "EXHIBITION",
        meetingPoint: "13:50 / 1층 로비",
        recruitmentDeadline: "2026-08-21T14:59:00.000Z",
        waitlistEnabled: true,
        cost: {
          type: "INDIVIDUAL_PURCHASE",
          estimatedPrice: 18000,
          purchaseUrl: null,
          purchaseNote: "티켓은 각자 예매해 주세요.",
        },
        bringItems: null,
        notice: null,
      },
    },
    {
      id: MOCK_PROGRAM_IDS.workshop,
      code: "OA / G029",
      type: "GATHERING",
      title: "작은 목재 오브젝트 만들기",
      description: "손에 잡히는 작은 목재 오브젝트를 직접 설계하고 만들어 봅니다.",
      hostId: "user-host-workshop",
      startAt: "2026-08-29T04:00:00.000Z",
      endAt: "2026-08-29T08:00:00.000Z",
      location: "을지로 목공 작업실",
      mapUrl: null,
      capacity: 6,
      status: "OPEN",
      coverImageId: null,
      createdAt: "2026-08-02T04:00:00.000Z",
      updatedAt: "2026-08-02T04:00:00.000Z",
      detail: {
        programId: MOCK_PROGRAM_IDS.workshop,
        category: "WORKSHOP",
        meetingPoint: "작업실 1층 입구",
        recruitmentDeadline: "2026-08-26T14:59:00.000Z",
        waitlistEnabled: true,
        cost: {
          type: "HOST_COLLECT",
          participationFee: 25000,
          feeIncludes: "목재와 기본 공구",
          paymentInfo: "참가 확정 후 호스트가 입금 정보를 안내합니다.",
          paymentDeadline: "2026-08-27T14:59:00.000Z",
          cancellationPolicy: "재료 준비 이후에는 환불이 어렵습니다.",
        },
        bringItems: "작업용 앞치마",
        notice: null,
      },
    },
    {
      id: MOCK_PROGRAM_IDS.reading,
      code: "OA / R030",
      type: "READING",
      title: "건축 없는 건축",
      description: "건물을 짓는 일 바깥에서 건축적 태도가 어떻게 작동하는지 읽고 이야기합니다.",
      hostId: "user-host-reading",
      startAt: "2026-08-16T10:30:00.000Z",
      endAt: "2026-08-16T12:30:00.000Z",
      location: "연남동 OA ROOM",
      mapUrl: null,
      capacity: 10,
      status: "OPEN",
      coverImageId: null,
      createdAt: "2026-07-28T02:00:00.000Z",
      updatedAt: "2026-07-28T02:00:00.000Z",
      detail: {
        programId: MOCK_PROGRAM_IDS.reading,
        resourceTitle: "건축 없는 건축",
      },
    },
  ];

  const participations: Participation[] = [
    ...MEMBER_IDS.map((userId, index) =>
      participation(
        `participation-exhibition-${index + 1}`,
        MOCK_PROGRAM_IDS.exhibition,
        userId,
        `2026-08-0${index + 1}T03:00:00.000Z`,
      ),
    ),
    ...MEMBER_IDS.slice(0, 4).map((userId, index) =>
      participation(
        `participation-workshop-${index + 1}`,
        MOCK_PROGRAM_IDS.workshop,
        userId,
        `2026-08-0${index + 2}T05:00:00.000Z`,
        index < 3 ? "PAID" : "PENDING",
      ),
    ),
    ...MEMBER_IDS.map((userId, index) =>
      participation(
        `participation-reading-${index + 1}`,
        MOCK_PROGRAM_IDS.reading,
        userId,
        `2026-07-${20 + index}T03:00:00.000Z`,
      ),
    ),
  ];

  const records: ProgramRecord[] = [
    {
      id: "record-027",
      programId: MOCK_PROGRAM_IDS.talk,
      authorId: "user-admin",
      what: "AI 시대의 인간 가치 창출과 데이터 기반 브랜드 전략",
      found: "기술이 평준화될수록 관점과 맥락을 만드는 인간의 역할이 중요해집니다.",
      summary: "AI 시대의 인간 가치 창출과 데이터 기반 브랜드 전략",
      body: "기술이 평준화될수록 관점과 맥락을 만드는 인간의 역할이 중요해집니다.",
      photoMediaId: null,
      linkUrl: null,
      createdAt: "2026-08-07T13:00:00.000Z",
    },
  ];

  const approvals: ProgramApproval[] = [
    {
      id: "approval-talk-027",
      programId: MOCK_PROGRAM_IDS.talk,
      requesterId: "user-admin",
      reviewerId: null,
      status: "NOT_REQUIRED",
      requestedAt: null,
      reviewedAt: null,
      reviewComment: null,
      publishedAt: "2026-08-07T13:00:00.000Z",
    },
    {
      id: "approval-gathering-028",
      programId: MOCK_PROGRAM_IDS.exhibition,
      requesterId: "user-host-exhibition",
      reviewerId: "user-admin",
      status: "APPROVED",
      requestedAt: "2026-07-30T01:00:00.000Z",
      reviewedAt: "2026-08-01T01:00:00.000Z",
      reviewComment: null,
      publishedAt: "2026-08-01T01:00:00.000Z",
    },
    {
      id: "approval-gathering-029",
      programId: MOCK_PROGRAM_IDS.workshop,
      requesterId: "user-host-workshop",
      reviewerId: "user-admin",
      status: "APPROVED",
      requestedAt: "2026-07-31T04:00:00.000Z",
      reviewedAt: "2026-08-02T04:00:00.000Z",
      reviewComment: null,
      publishedAt: "2026-08-02T04:00:00.000Z",
    },
    {
      id: "approval-reading-030",
      programId: MOCK_PROGRAM_IDS.reading,
      requesterId: "user-host-reading",
      reviewerId: null,
      status: "NOT_REQUIRED",
      requestedAt: null,
      reviewedAt: null,
      reviewComment: null,
      publishedAt: "2026-08-01T00:00:00.000Z",
    },
  ];

  const messages: ProgramMessage[] = [
    {
      id: "message-exhibition-notice",
      programId: MOCK_PROGRAM_IDS.exhibition,
      authorId: "user-host-exhibition",
      type: "NOTICE",
      content: "집결 장소는 리움미술관 지상 1층 안내 데스크 앞입니다.",
      parentId: null,
      isPinned: true,
      isHidden: false,
      createdAt: "2026-08-08T01:00:00.000Z",
      editedAt: null,
    },
    {
      id: "message-exhibition-question",
      programId: MOCK_PROGRAM_IDS.exhibition,
      authorId: MEMBER_IDS[0],
      type: "QUESTION",
      content: "전시 티켓은 각자 미리 예매하면 될까요?",
      parentId: null,
      isPinned: false,
      isHidden: false,
      createdAt: "2026-08-08T02:00:00.000Z",
      editedAt: null,
    },
    {
      id: "message-exhibition-reply",
      programId: MOCK_PROGRAM_IDS.exhibition,
      authorId: "user-host-exhibition",
      type: "CHAT",
      content: "네, 14시 입장 회차로 개별 예매해 주세요.",
      parentId: "message-exhibition-question",
      isPinned: false,
      isHidden: false,
      createdAt: "2026-08-08T02:20:00.000Z",
      editedAt: null,
    },
    {
      id: "message-exhibition-chat",
      programId: MOCK_PROGRAM_IDS.exhibition,
      authorId: MEMBER_IDS[1],
      type: "CHAT",
      content: "저는 지하철로 이동해서 로비에서 바로 합류하겠습니다.",
      parentId: null,
      isPinned: false,
      isHidden: false,
      createdAt: "2026-08-08T03:00:00.000Z",
      editedAt: null,
    },
    {
      id: "message-reading-notice",
      programId: MOCK_PROGRAM_IDS.reading,
      authorId: "user-host-reading",
      type: "NOTICE",
      content: "이번 주 읽기 범위는 42쪽부터 87쪽까지입니다.",
      parentId: null,
      isPinned: true,
      isHidden: false,
      createdAt: "2026-08-08T05:00:00.000Z",
      editedAt: null,
    },
    {
      id: "message-reading-question",
      programId: MOCK_PROGRAM_IDS.reading,
      authorId: MEMBER_IDS[2],
      type: "QUESTION",
      content: "토론에서 참고할 사례를 하나씩 준비하면 될까요?",
      parentId: null,
      isPinned: false,
      isHidden: false,
      createdAt: "2026-08-08T05:30:00.000Z",
      editedAt: null,
    },
    {
      id: "message-reading-reply",
      programId: MOCK_PROGRAM_IDS.reading,
      authorId: "user-host-reading",
      type: "CHAT",
      content: "좋습니다. 공간이 아닌 실천 사례도 환영합니다.",
      parentId: "message-reading-question",
      isPinned: false,
      isHidden: false,
      createdAt: "2026-08-08T06:00:00.000Z",
      editedAt: null,
    },
    {
      id: "message-reading-chat",
      programId: MOCK_PROGRAM_IDS.reading,
      authorId: MEMBER_IDS[3],
      type: "CHAT",
      content: "저는 공공 프로젝트 사례를 가져가겠습니다.",
      parentId: null,
      isPinned: false,
      isHidden: false,
      createdAt: "2026-08-08T06:30:00.000Z",
      editedAt: null,
    },
  ];

  const messageReactions: MessageReaction[] = [
    ...[
      [MEMBER_IDS[0], "❤️"],
      [MEMBER_IDS[1], "❤️"],
      [MEMBER_IDS[2], "❤️"],
      [MEMBER_IDS[3], "👍"],
      ["user-host-exhibition", "👍"],
    ].map(([userId, emoji], index) => ({
      id: `reaction-exhibition-question-${index + 1}`,
      programId: MOCK_PROGRAM_IDS.exhibition,
      messageId: "message-exhibition-question",
      userId,
      emoji: emoji as MessageReaction["emoji"],
      createdAt: `2026-08-08T02:${String(index + 1).padStart(2, "0")}:00.000Z`,
      updatedAt: `2026-08-08T02:${String(index + 1).padStart(2, "0")}:00.000Z`,
    })),
    ...MEMBER_IDS.slice(0, 4).map((userId, index) => ({
      id: `reaction-exhibition-reply-${index + 1}`,
      programId: MOCK_PROGRAM_IDS.exhibition,
      messageId: "message-exhibition-reply",
      userId,
      emoji: "✅" as const,
      createdAt: `2026-08-08T02:${String(30 + index).padStart(2, "0")}:00.000Z`,
      updatedAt: `2026-08-08T02:${String(30 + index).padStart(2, "0")}:00.000Z`,
    })),
    ...MEMBER_IDS.slice(0, 2).map((userId, index) => ({
      id: `reaction-exhibition-notice-${index + 1}`,
      programId: MOCK_PROGRAM_IDS.exhibition,
      messageId: "message-exhibition-notice",
      userId,
      emoji: "👏" as const,
      createdAt: `2026-08-08T01:${String(index + 1).padStart(2, "0")}:00.000Z`,
      updatedAt: `2026-08-08T01:${String(index + 1).padStart(2, "0")}:00.000Z`,
    })),
  ];

  const pageContents: PageContent[] = [
    {
      id: "page-content-home",
      key: "home",
      title: "HOME",
      headline: "지금 OMNIVORE에서 일어나는 일",
      description: "가장 가까운 일정과 참여 가능한 Program을 확인합니다.",
      emptyState: "예정된 Program이 없습니다.",
      updatedAt: "2026-08-01T00:00:00.000Z",
      updatedBy: "user-admin",
    },
    {
      id: "page-content-programs",
      key: "programs",
      title: "PROGRAMS",
      headline: "PROGRAMS",
      description: "Talk, Reading, Gathering을 날짜 순서로 살펴봅니다.",
      emptyState: "조건에 맞는 Program이 없습니다.",
      updatedAt: "2026-08-01T00:00:00.000Z",
      updatedBy: "user-admin",
    },
    {
      id: "page-content-talk",
      key: "talk",
      title: "TALK",
      headline: "강연",
      description: "OMNIVORE와 외부에서 열리는 Talk입니다.",
      emptyState: "등록된 Talk가 없습니다.",
      updatedAt: "2026-08-01T00:00:00.000Z",
      updatedBy: "user-admin",
    },
    {
      id: "page-content-reading",
      key: "reading",
      title: "READING",
      headline: "함께 읽기",
      description: "하나의 텍스트를 중심으로 모이는 Program입니다.",
      emptyState: "등록된 Reading이 없습니다.",
      updatedAt: "2026-08-01T00:00:00.000Z",
      updatedBy: "user-admin",
    },
    {
      id: "page-content-gathering",
      key: "gathering",
      title: "번개",
      headline: "GATHERING",
      description: "멤버가 제안하고 운영진이 승인한 모임입니다.",
      emptyState: "참여 가능한 Gathering이 없습니다.",
      updatedAt: "2026-08-01T00:00:00.000Z",
      updatedBy: "user-admin",
    },
    {
      id: "page-content-members",
      key: "members",
      title: "MEMBERS",
      headline: "OMNIVORE MEMBERS",
      description: "함께 활동하는 멤버를 확인합니다.",
      emptyState: "표시할 Member가 없습니다.",
      updatedAt: "2026-08-01T00:00:00.000Z",
      updatedBy: "user-admin",
    },
    {
      id: "page-content-about",
      key: "about",
      title: "ABOUT",
      headline: "OMNIVORE ARCHITECT",
      description: "활동을 만들고, 사람이 모이고, 대화하고, 기록이 남는 시스템.",
      emptyState: "",
      updatedAt: "2026-08-01T00:00:00.000Z",
      updatedBy: "user-admin",
    },
  ];

  return {
    schemaVersion: MOCK_SCHEMA_VERSION,
    revision: 0,
    users,
    programs,
    approvals,
    programRevisions: [],
    participations,
    records,
    recordMaterials: [],
    activities: [],
    messages,
    messageReactions,
    participatingSeasonsByUserId,
    pageContents,
  };
}
